tools_recognition:
  ros__parameters:

    # Detection threshold (confidence level)
    threshold: 0.8

    # YOLOv8 model file path
    model_file: yolov8n.pt

    # Start recognition automatically on node initialization
    start_on_init: true

    # 3D bounding box size limits (in meters)
    max_sizes:
        - [0.05, 0.05, 0.05]

    # Subscriber configuration
    subscribers:
      
      slop: 0.2 # meters
      qos_profile: 10 # depth

      image_rgb: /micky_vision/camera/color/image_raw
      camera_info: /micky_vision/camera/color/camera_info
      image_depth: /micky_vision/camera/aligned_depth_to_color/image_raw

    # Publisher configuration
    publishers:

      object_recognition:
        topic: /micky_vision/tools_recognition
        qos_profile: 10

      debug:
        topic: /micky_vision/tools_classes
        qos_profile: 10

    # Service configuration
    services:
    
      object_recognition:
        start: /micky_vision/recognition_start
        stop: /micky_vision/recognition_stop